/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Frames.Panels.Student_AddPanel;
import Frames.Panels.Student_ListPanel;
import Frames.Panels.Student_UpdatePanel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author vbnfv
 */
public class Admin_StudentsFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form Admin_StudentsFrame
     */
    Student_AddPanel p1;
    Student_ListPanel p2;
    Student_UpdatePanel p3;
    GridBagLayout layout=new GridBagLayout();
    public Admin_StudentsFrame() {
        initComponents();
        p1=new Student_AddPanel();
        p2=new Student_ListPanel();
        p3=new Student_UpdatePanel();
        DynamicPanal.setLayout(layout);
        GridBagConstraints c=new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        DynamicPanal.add(p1,c);
        DynamicPanal.add(p2,c);
        DynamicPanal.add(p3,c);
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonList = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        DynamicPanal = new javax.swing.JPanel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(132, 30, 98));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 55, 58), 1, true));

        jButtonAdd.setBackground(new java.awt.Color(132, 30, 98));
        jButtonAdd.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(243, 170, 32));
        jButtonAdd.setText("Add Student");
        jButtonAdd.setBorder(null);
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonList.setBackground(new java.awt.Color(132, 30, 98));
        jButtonList.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButtonList.setForeground(new java.awt.Color(243, 170, 32));
        jButtonList.setText("List Student");
        jButtonList.setBorder(null);
        jButtonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListActionPerformed(evt);
            }
        });

        jButtonUpdate.setBackground(new java.awt.Color(132, 30, 98));
        jButtonUpdate.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(243, 170, 32));
        jButtonUpdate.setText("Update Student");
        jButtonUpdate.setBorder(null);
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jButtonUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonUpdateKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
            .addComponent(jButtonList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButtonAdd)
                .addGap(100, 100, 100)
                .addComponent(jButtonList)
                .addGap(108, 108, 108)
                .addComponent(jButtonUpdate)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        DynamicPanal.setBackground(new java.awt.Color(243, 170, 32));

        javax.swing.GroupLayout DynamicPanalLayout = new javax.swing.GroupLayout(DynamicPanal);
        DynamicPanal.setLayout(DynamicPanalLayout);
        DynamicPanalLayout.setHorizontalGroup(
            DynamicPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 959, Short.MAX_VALUE)
        );
        DynamicPanalLayout.setVerticalGroup(
            DynamicPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListActionPerformed
        // TODO add your handling code here:
        p2.setVisible(true);
        p1.setVisible(false);
        p3.setVisible(false);
    }//GEN-LAST:event_jButtonListActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        p3.setVisible(true);
        p1.setVisible(false);
        p2.setVisible(false);
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonUpdateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonUpdateKeyReleased
        // TODO add your handling code here:
//        Frames.Panels.Student_ListPanel r=new Student_ListPanel();
//        r.gettable().setModel(cistomModel(r.gettable()));
        //jTable1.setModel(cistomModel(jTable1));
//        p2.setVisible(true);
//        p1.setVisible(false);
//        p3.setVisible(false);
    }//GEN-LAST:event_jButtonUpdateKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanal;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonList;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
