/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Panels;

import static database.student_database.connect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vbnfv
 */
public class Assign_studentsPanel extends javax.swing.JPanel {

    /**
     * Creates new form Assign_studentsPanel
     */
    public Assign_studentsPanel() {
        initComponents();
    }
    protected void resetPanalDeta(){
        jTextField1.setText("");
        jTextField2.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(0);
        
    }
    public int UnacceptableRepetition(){
        
        Object database[]=new Object[]{(String) jComboBox1.getSelectedItem(),
                    (String) jComboBox2.getSelectedItem(),
                    (String) jComboBox3.getSelectedItem(),
                    (String) jComboBox4.getSelectedItem()};
        int x=1;
        for (int j = 0; j < database.length-1; j++) {
            for (int i = j; i < database.length-1; i++) {
                if(database[j].equals(database[i+1])){
                     x=0;
                    break;
                }
            }
        }
        
        return x;
    }
    public JTextField getTextFild(){
        return jTextField1;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 28, 21));

        jButton1.setBackground(new java.awt.Color(216, 243, 220));
        jButton1.setForeground(new java.awt.Color(8, 28, 21));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(216, 243, 220));
        jTextField1.setForeground(new java.awt.Color(8, 28, 21));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(216, 243, 220));
        jTextField2.setForeground(new java.awt.Color(27, 67, 50));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(216, 243, 220));
        jComboBox1.setForeground(new java.awt.Color(27, 67, 50));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PL2", "DS", "DB1", "LD", "NULL" }));

        jComboBox2.setBackground(new java.awt.Color(183, 228, 199));
        jComboBox2.setForeground(new java.awt.Color(27, 67, 50));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PL2", "DS", "DB1", "LD", "NULL" }));

        jComboBox3.setBackground(new java.awt.Color(183, 228, 199));
        jComboBox3.setForeground(new java.awt.Color(27, 67, 50));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PL2", "DS", "DB1", "LD", "NULL" }));

        jComboBox4.setBackground(new java.awt.Color(149, 213, 178));
        jComboBox4.setForeground(new java.awt.Color(27, 67, 50));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PL2", "DS", "DB1", "LD", "NULL" }));

        jButton3.setBackground(new java.awt.Color(27, 67, 50));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(82, 183, 136));
        jButton3.setText("Assigned");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(216, 243, 220));
        jLabel1.setText("Name");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(216, 243, 220));
        jLabel2.setText("Subject 1");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(183, 228, 199));
        jLabel3.setText("Subject 2");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(183, 228, 199));
        jLabel4.setText("Subject 3");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(149, 213, 178));
        jLabel5.setText("Subject 4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(159, 159, 159)
                .addComponent(jButton3)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            Connection con=connect();
            String sql="select *  from student where id=?";
            ResultSet r;
            try (PreparedStatement p = con.prepareStatement(sql)) {
                p.setString(1, jTextField1.getText());
                r = p.executeQuery();
                if(r.next()){
                    
                    jTextField2.setText(r.getString("fname"));
                }
//            else if(!searchTextField.getText().equals("")){
//                
//            }
                else
                {
                    JOptionPane.showMessageDialog(null, "ID not found in table", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            r.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public int search_Assigned_Student(){
        int H =0; 
        try {
            // TODO add your handling code here:
            Connection con=connect();
            String sql="select *  from subject";
            ResultSet r;
            try (PreparedStatement p = con.prepareStatement(sql)) {
                //p.setString(1, jTextField1.getText());
                r = p.executeQuery();
                while(r.next()){
                    if(jTextField1.getText().equals(r.getString("student_id"))){
                        H = 1;
                        break;
                    }
                    else{
                        H = 0;
                    }
                    
                }
//            else if(!searchTextField.getText().equals("")){
//                
//            }
            }
            
            r.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
         return H ;
     }
    public static void update_subject(String id, String s1, String s2, String s3, String s4) throws SQLException {
        try {
            Connection con = connect();
            PreparedStatement p = con.prepareStatement("update subject (student_id,s1,s2,s3,s4) values(?,?,?,?,?)");
            p.setInt(1, Integer.parseInt(id));
            p.setString(2, s1);
            p.setString(3, s2);
            p.setString(4, s3);
            p.setString(5, s4);
            p.execute();
            p.close();
        } catch (SQLException ee) {
            JOptionPane.showMessageDialog(null, ee.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    public void update_Assigned_Student(){
        try {
            // TODO add your handling code here:
            String student_id=jTextField1.getText();
            String s1=(String) jComboBox1.getSelectedItem();
            String s2=(String) jComboBox2.getSelectedItem();
            String s3=(String) jComboBox3.getSelectedItem();
            String s4=(String) jComboBox4.getSelectedItem();
            Connection con=connect();
            String sql="update subject set s1='"+s1+"',s2='"+s2+"',s3='"+s3+"',s4='"+s4+"' where student_id='"+student_id+"' ";
            PreparedStatement p=con.prepareStatement(sql);
            p.execute();
            /*Lecturer_ListPanel o=new Lecturer_ListPanel();
            DefaultTableModel model=(DefaultTableModel)o.gettable().getModel();
            model.setRowCount(0);*/
            
                JOptionPane.showMessageDialog(null,"Update successfully");
            p.close();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(search_Assigned_Student()==1){
            if (UnacceptableRepetition()==1) {
                update_Assigned_Student();
            }
            else{
                JOptionPane.showMessageDialog(null, "The student cannot be assigned to the same course more than once", "Unacceptable repetition", JOptionPane.ERROR_MESSAGE);
            }
            
        }else{
            switch (UnacceptableRepetition()) {
            case 0:
                JOptionPane.showMessageDialog(null, "The student cannot be assigned to the same course more than once", "Unacceptable repetition", JOptionPane.ERROR_MESSAGE);
                
                break;
            case 1:
                try {
                    // TODO add your handling code here:
                    database.subject_database.insert_subject(jTextField1.getText(),
                            (String) jComboBox1.getSelectedItem(),
                            (String) jComboBox2.getSelectedItem(),
                            (String) jComboBox3.getSelectedItem(),
                            (String) jComboBox4.getSelectedItem());
                    resetPanalDeta();
                    JOptionPane.showMessageDialog(null, "Update successfully");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }   break;
            default:
                JOptionPane.showMessageDialog(null, " Error in Case 0or1 Line 278  ", "Unacceptable repetition", JOptionPane.ERROR_MESSAGE);
                break;
        }
        
        
        }
            

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
