/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Panels;
import static database.student_database.connect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author vbnfv
 */
public class Student_ListPanel extends javax.swing.JPanel {

    /**
     * Creates new form Student_ListPanel
     */
//    String data[][];
//    ArrayList<students> arr=student_database.get_student();
    public Student_ListPanel() {
        initComponents();
        jTable1.setModel(cistomModel(jTable1));
        
    }
    public JTable gettable(){
        return jTable1;
    }
    
//    private void show_data()
//    {
//        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
//        data=new String[arr.size()][6];
//        for (int i = 0; i < arr.size(); i++) {
//            data[i][0]=""+arr.get(i).getId();
//            data[i][1]=arr.get(i).getFname();
//            data[i][2]=arr.get(i).getLname();
//            data[i][3]=arr.get(i).getEmail();
//            data[i][4]=arr.get(i).getPassword();
//            data[i][5]=""+arr.get(i).getAge();
//            model.addRow(data);
//        }
//        jTable1=new JTable(model); 
//        jScrollPane1=new JScrollPane(jTable1);
//        add(jScrollPane1);
//            
//        
//    }
    public static DefaultTableModel cistomModel(JTable table)
    {
        DefaultTableModel model=(DefaultTableModel)table.getModel();
        model.setRowCount(0);
        try {
            Connection con=connect();
            String sql="select * from student ";
            PreparedStatement p=con.prepareStatement(sql);
            ResultSet r=p.executeQuery();
            if(r.isBeforeFirst())
            {
                while(r.next())
                {
                    Object dataobject[]={r.getString("id"),r.getString("fname"),
                    r.getString("lname"),
                    r.getString("email"),
                    r.getString("password"),
                    r.getString("age")};
                   model.addRow(dataobject);
                }
            }
            p.close();
            r.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        return model;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setBackground(new java.awt.Color(52, 107, 109));
        jTable1.setForeground(new java.awt.Color(243, 170, 32));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Email", "Password", "Age"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
